server:
  port: 9201

spring:
  application:
    name: demo-mall-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.26.203.218:5432/demo_mall_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: oizys
    password: ${PGSQL_PASSWD}
  profiles:
    active: @profile.active@  # 使用Maven profile变量