server:
  port: 9202

spring:
  application:
    name: demo-mall-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo_mall_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: oizys
    password: postgres123
  profiles:
    active: @profile.active@  # 使用Maven profile变量