server:
  port: 9100

spring:
  application:
    name: demo-mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
    gateway:
      routes:
        - id: user-service
          uri: lb://demo-mall-user
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: lb://demo-mall-product
          predicates:
            - Path=/api/product/**
        - id: order-service
          uri: lb://demo-mall-order
          predicates:
            - Path=/api/order/**
  profiles:
    active: @profile.active@  # 使用Maven profile变量